# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitterSource', models.CharField(max_length=100, unique=True)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('influencer', models.CharField(max_length=16)),
                ('followers', models.IntegerField()),
                ('following', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
