# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitterSource', models.CharField(max_length=100, unique=True)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('jobTitle', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100, null=True)),
                ('cdSize', models.CharField(max_length=40, null=True)),
                ('cdIndustry', models.CharField(max_length=40, null=True)),
                ('hqCity', models.CharField(max_length=20, null=True)),
                ('hqState', models.CharField(max_length=20, null=True)),
                ('hqCountry', models.CharField(max_length=20, null=True)),
                ('twitterUserName', models.CharField(default='No Handle Entered: 2017-02-23 23:45:08.254928', max_length=100, unique=True)),
                ('ngrams', models.CharField(max_length=10, null=True)),
                ('statuses_count', models.IntegerField(default=0)),
                ('influencer', models.BooleanField(default=False)),
                ('followers_count', models.IntegerField(null=True)),
                ('following_count', models.IntegerField(null=True)),
                ('description', models.TextField()),
                ('friends_count', models.IntegerField()),
                ('profile_image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweetId', models.CharField(max_length=100)),
                ('tweetRawText', models.CharField(max_length=140)),
                ('tweetProcText', models.CharField(max_length=140)),
                ('isBusiness', models.FloatField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_scraper.Profile')),
            ],
        ),
    ]
