# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='handle',
            field=models.CharField(default='No Handle Entered', max_length=100, unique=True),
        ),
    ]
