# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_scraper', '0002_profile_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.IntegerField(null=True),
        ),
    ]
