# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_scraper', '0003_auto_20170223_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='job',
            new_name='jobTitle',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='handle',
            new_name='twitterUserName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
        migrations.AddField(
            model_name='profile',
            name='cdIndustry',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cdSize',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hqCity',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hqCountry',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hqState',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
