# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_scraper', '0005_auto_20170223_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='topBusinessTerms',
            field=models.CharField(default='Thought Leadership,Businessing,Enterprise', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='topPersonalTerms',
            field=models.CharField(default='Family,Vacation,Pets', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitterUserName',
            field=models.CharField(default='No Handle Entered: 2017-02-24 00:28:09.591660', max_length=100, unique=True),
        ),
    ]
