# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_scraper', '0006_auto_20170224_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='twitterUserName',
            field=models.CharField(default='No Handle Entered: 2017-02-24 00:28:28.118559', max_length=100, unique=True),
        ),
    ]
