# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 01:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_scraper', '0007_auto_20170224_0028'),
        ('profile_scraper', '0006_auto_20170224_0012'),
    ]

    operations = [
    ]
