# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_scraper', '0018_auto_20170223_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ngrams',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitterUserName',
            field=models.CharField(default='No Handle Entered: 2017-02-23 19:35:34.442006', max_length=100, unique=True),
        ),
    ]
