# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_scraper', '0016_auto_20170223_1443'),
        ('profile_scraper', '0024_auto_20170223_1956'),
    ]

    operations = [
    ]
