# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_scraper', '0025_merge_20170223_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweetId', models.CharField(max_length=100)),
                ('tweetRawText', models.CharField(max_length=140)),
                ('tweetProcText', models.CharField(max_length=140)),
                ('isBusiness', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='numTweets',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitterUserName',
            field=models.CharField(default='No Handle Entered: 2017-02-23 21:20:17.939243', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_scraper.Profile'),
        ),
    ]
