# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_scraper', '0026_auto_20170223_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='numTweets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitterUserName',
            field=models.CharField(default='No Handle Entered: 2017-02-23 22:26:02.949893', max_length=100, unique=True),
        ),
    ]
